name: fluid_bottom_nav_bar
description: A beautiful bottom navigation with a fluid animation. Bar color, icons and animation speed are fully customizable.
version: 1.3.0
homepage: https://github.com/eric-taix/fluid-nav-bar
repository: https://github.com/eric-taix/fluid-nav-bar

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
