name: fluid_bottom_nav_bar
description: A beautiful bottom navigation with a fluid animation. Bar color, icons and animation speed are fully customizable.
version: 1.0.1
homepage: https://github.com/eric-taix/fluid-nav-bar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
