name: fluid_bottom_nav_bar
description: A beautiful bottom navigation with a fluid animation. Bar color, icons and animation speed are fully customizable.
version: 1.3.0
homepage: https://github.com/eric-taix/fluid-nav-bar
repository: https://github.com/eric-taix/fluid-nav-bar

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.11.0-0.1.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
